# Generated by Django 4.2.7 on 2026-09-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-timestamp"], name="auditlog_au_timesta_a26c2b_idx"
            ),
        ),
    ]
