# Generated by Django 4.2.7 on 2026-09-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_casetask_caselink_casecomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="state",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
