# Generated by Django 4.2.7 on 2026-09-10 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_case_state"),
        ("icjs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icjsimportlog",
            name="case",
            field=models.ForeignKey(
                blank=True,
                help_text="Null when a totally-failed import removed its empty case; the log row itself always survives for audit.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="icjs_imports",
                to="cases.case",
            ),
        ),
    ]
