# Generated by Django 4.2.7 on 2026-09-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_remove_alert_is_read_alert_dedupe_key_alert_refs_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "read", "-created_at"],
                name="alerts_noti_user_id_4b0072_idx",
            ),
        ),
    ]
