"use client";

import { useState } from "react";
import { api } from "@/lib/api";

type Citation = {
  evidence_id: number | null;
  file_name: string;
  case_fir?: string;
  snippet: string;
  score?: number;
  method?: string;
};
type Turn = {
  question: string;
  intent: string;
  answer: string;
  citations: Citation[];
  generated: boolean;
  model?: string;
};

const SUGGESTED = [
  "Summarize the key players",
  "How is Rahul Sharma connected to Vikram Patil?",
  "What vehicles were mentioned?",
];

/** Investigation copilot chat: path QA, summaries, and RAG answers —
 *  every claim cites its evidence. */
export function CopilotPanel({ caseId }: { caseId?: string }) {
  const [turns, setTurns] = useState<Turn[]>([]);
  const [input, setInput] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  async function ask(question: string) {
    const q = question.trim();
    if (!q || busy) return;
    setBusy(true);
    setError("");
    setInput("");
    try {
      const r = await api.copilot(q, caseId);
      setTurns((t) => [...t, {
        question: q, intent: r.intent, answer: r.answer,
        citations: r.citations ?? [], generated: !!r.generated, model: r.model,
      }]);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Copilot failed");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="card">
      <div className="flex items-center justify-between">
        <h2 className="font-semibold">Investigation copilot</h2>
        <span className="text-xs text-slate-500">graph paths · summaries · evidence-grounded RAG</span>
      </div>
      <div className="mt-2 flex flex-wrap gap-2">
        {SUGGESTED.map((s) => (
          <button key={s} className="rounded-full border border-ink-700 px-2.5 py-0.5 text-xs text-slate-300 hover:border-accent hover:text-accent"
            onClick={() => ask(s)}>
            {s}
          </button>
        ))}
      </div>
      <div className="mt-3 max-h-96 space-y-3 overflow-y-auto">
        {turns.map((t, i) => (
          <div key={i} className="rounded-lg bg-ink-950 p-3 text-sm">
            <p className="font-semibold text-slate-100">Q: {t.question}</p>
            <p className="mt-1 text-xs text-slate-500">
              {t.intent}{t.generated ? ` · generated by ${t.model}` : " · evidence-backed (no LLM)"}
            </p>
            <p className="mt-1 whitespace-pre-wrap text-slate-200">{t.answer}</p>
            {t.citations.length > 0 && (
              <ul className="mt-2 space-y-1 border-t border-ink-700 pt-2 text-xs text-slate-400">
                {t.citations.map((c, j) => (
                  <li key={j}>
                    <b className="text-accent">[{j + 1}] {c.file_name || c.case_fir || "registry"}</b>{" "}
                    {c.snippet}
                    {typeof c.score === "number" && <span className="text-slate-500"> ({(c.score * 100).toFixed(0)}%)</span>}
                  </li>
                ))}
              </ul>
            )}
          </div>
        ))}
        {turns.length === 0 && (
          <p className="py-2 text-sm text-slate-500">Ask about connections, key players, or anything in the evidence.</p>
        )}
      </div>
      {error && <p className="mt-2 text-sm text-risk-high">{error}</p>}
      <form className="mt-3 flex gap-2" onSubmit={(e) => { e.preventDefault(); ask(input); }}>
        <input className="input" placeholder="Ask the copilot…" value={input}
          onChange={(e) => setInput(e.target.value)} disabled={busy} />
        <button className="btn" type="submit" disabled={busy}>{busy ? "…" : "Ask"}</button>
      </form>
    </div>
  );
}
