# Generated by Django 4.2.7 on 2026-09-09 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("evidence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="classification_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ocr_engine",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ocr_pages",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ocr_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="evidence",
            name="processing_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="evidence",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ChainOfCustody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evidence_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("viewed", "Viewed"),
                            ("downloaded", "Downloaded"),
                            ("classified", "Auto-classified"),
                            ("ocr_completed", "OCR completed"),
                            ("reprocessed", "Reprocessed"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=32,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custody_entries",
                        to="evidence.evidence",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["evidence", "timestamp"],
                        name="evidence_ch_evidenc_74c160_idx",
                    )
                ],
            },
        ),
    ]
