# Generated by Django 4.2.7 on 2026-09-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0003_documentchunk_documentchunk_uniq_chunk_per_evidence"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["case", "-created_at"], name="evidence_ev_case_id_861499_idx"
            ),
        ),
    ]
