# Generated by Django 4.2.7 on 2026-09-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0004_evidence_evidence_ev_case_id_861499_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chainofcustody",
            name="action",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("viewed", "Viewed"),
                    ("downloaded", "Downloaded"),
                    ("classified", "Auto-classified"),
                    ("ocr_completed", "OCR completed"),
                    ("reprocessed", "Reprocessed"),
                    ("deleted", "Deleted"),
                    ("icjs_import", "ICJS import"),
                ],
                max_length=32,
            ),
        ),
    ]
