# Generated by Django 4.2.7 on 2026-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0005_alter_chainofcustody_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="detected_language",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="evidence",
            name="detected_language_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="evidence",
            name="extraction_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
