# Generated by Django 4.2.7 on 2026-09-09 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("evidence", "0002_evidence_classification_confidence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("Person", "Person"),
                            ("Organization", "Organization"),
                            ("Location", "Location"),
                            ("Vehicle", "Vehicle"),
                            ("PhoneNumber", "Phone number"),
                            ("Event", "Event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(max_length=512)),
                ("normalized", models.CharField(db_index=True, max_length=512)),
                ("confidence", models.FloatField(default=0.0)),
                ("engine", models.CharField(blank=True, default="", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("merged", "Merged into another entity"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("mention_count", models.IntegerField(default=1)),
                ("graph_key", models.CharField(blank=True, default="", max_length=640)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_entities",
                        to="cases.case",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first_seen_entities",
                        to="evidence.evidence",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_from",
                        to="graph_api.extractedentity",
                    ),
                ),
            ],
            options={
                "ordering": ("-confidence", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="MergeSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("reason", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending decision"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_suggestions",
                        to="cases.case",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_as_a",
                        to="graph_api.extractedentity",
                    ),
                ),
                (
                    "entity_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_as_b",
                        to="graph_api.extractedentity",
                    ),
                ),
            ],
            options={
                "ordering": ("-score",),
            },
        ),
        migrations.CreateModel(
            name="ExtractedRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edge_type", models.CharField(max_length=32)),
                ("confidence", models.FloatField(default=0.0)),
                ("snippet", models.TextField(blank=True, default="")),
                ("engine", models.CharField(blank=True, default="", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("merged", "Merged into another entity"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_relations",
                        to="cases.case",
                    ),
                ),
                (
                    "dst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_relations",
                        to="graph_api.extractedentity",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first_seen_relations",
                        to="evidence.evidence",
                    ),
                ),
                (
                    "src",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_relations",
                        to="graph_api.extractedentity",
                    ),
                ),
            ],
            options={
                "ordering": ("-confidence",),
            },
        ),
        migrations.AddConstraint(
            model_name="mergesuggestion",
            constraint=models.UniqueConstraint(
                fields=("case", "entity_a", "entity_b"), name="uniq_merge_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="extractedrelation",
            constraint=models.UniqueConstraint(
                fields=("case", "src", "dst", "edge_type"),
                name="uniq_relation_per_case",
            ),
        ),
        migrations.AddConstraint(
            model_name="extractedentity",
            constraint=models.UniqueConstraint(
                fields=("case", "node_type", "normalized"), name="uniq_entity_per_case"
            ),
        ),
    ]
