# Generated by Django 4.2.7 on 2026-09-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph_api", "0002_extractedrelation_valid_from_graphsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedentity",
            name="geo_source",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="extractedentity",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractedentity",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
