# Generated by Django 4.2.7 on 2026-09-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "graph_api",
            "0003_extractedentity_geo_source_extractedentity_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="extractedentity",
            index=models.Index(
                fields=["case", "status"], name="graph_api_e_case_id_ad9742_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractedrelation",
            index=models.Index(
                fields=["case", "status"], name="graph_api_e_case_id_5598f7_idx"
            ),
        ),
    ]
