# Generated by Django 4.2.7 on 2026-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph_api", "0004_extractedentity_graph_api_e_case_id_ad9742_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedentity",
            name="native_snippet",
            field=models.TextField(blank=True, default=""),
        ),
    ]
